sonar.projectKey=flowboard-frontend
sonar.projectName=flowboard-frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,src/main.ts,src/environments/**,src/app/app.config.ts,src/app/app.routes.ts,src/app/core/models/**,src/app/core/guards/**,src/app/store/board/board.effects.ts,src/app/features/auth/auth.routes.ts,src/app/features/admin/admin.routes.ts,src/app/features/board/board.component.ts,src/app/features/board/card-detail/**,src/app/features/workspace/workspace.component.ts,src/app/features/dashboard/dashboard.component.ts,src/app/features/billing/premium-membership.component.ts,src/app/features/guest-dashboard/guest-dashboard.component.ts,src/app/features/admin/admin-dashboard/**,src/app/features/admin/platform-management/**,src/app/features/admin/user-management/**,src/app/features/admin/overdue-cards/**,src/app/features/admin/activity-reports/**,src/app/features/admin/audit-logs/**,src/app/features/admin/broadcasts/**,src/app/features/admin/platform-analytics/**
sonar.javascript.lcov.reportPaths=coverage/flowboard-frontend/lcov.info
